# Change the title, it's for you. Maybe you see "My newspaper"?
title: SURVEYOR NEWS
# Options: light, sepia or dark
theme: light
# Options: daily, weekly or all
edition: weekly
feeds:
  - https://landsurveyorsunited.com/video/feed/all
  - https://landsurveyorsunited.com/photo/feed/all
