title: RSSPaper
# Options: light or dark
theme: dark
# Options: daily, yesterday, weekly or all
edition: yesterday
feeds:
  - https://programadorwebvalencia.com/feed/
  - https://republicaweb.es/feed/
